# 公開するページのURL
baseURL = "https://akikuno.github.io/blog/"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
summaryLength  = 120
enableRobotsTXT = true

# ブログのタイトル
title = "Bioinfo Blog"

theme = "mainroad"
paginate = 5

# メインメニュー
[[Menus.main]]
  Name = "ホーム"
  URL = "/"
[[Menus.main]]
  Name = "投稿一覧"
  URL = "/posts/"

# 自己紹介
[Author]
    name = "久野 朗広/Akihiro Kuno"
    bio = ""
    avatar = "img/avatar.jpg"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Akihiro Kuno"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#8db1ab"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "akikuno_sh"
  github = "akikuno"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "false"
    widgets = ["search", "recent", "categories", "taglist", "social", "twitter"]

